# Generated by Django 5.0.6 on 2024-05-31 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='return_date',
            field=models.DateField(null=True),
        ),
    ]
