# Generated by Django 5.0.6 on 2024-05-31 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lend', '0002_alter_lend_return_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lend',
            name='return_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
